name: Nightly Benchmarks

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: Restore
        run: dotnet restore AssemblyChain-Core.sln
      - name: Run Benchmarks
        run: dotnet run --project tests/AssemblyChain.Benchmarks/AssemblyChain.Benchmarks.csproj -- --artifacts ../../artifacts/benchmarks
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: artifacts/benchmarks
